default["graphite"]["version"]                              = "0.9.10"
default["graphite"]["carbon"]["line_receiver_interface"]    = "127.0.0.1"
default["graphite"]["carbon"]["pickle_receiver_interface"]  = "127.0.0.1"
default["graphite"]["carbon"]["cache_query_interface"]      = "127.0.0.1"
default["graphite"]["dashboard"]["timezone"]                = "America/New_York"
default["graphite"]["dashboard"]["memcache_hosts"]          = [ "127.0.0.1:11211" ]
# default["graphite"]["templates"]["default"]["background"]   = 
# default["graphite"]["templates"]["default"]["foreground"]   = 
# default["graphite"]["templates"]["default"]["majorLine"]    = 
# default["graphite"]["templates"]["default"]["minorLine"]    = 
# default["graphite"]["templates"]["default"]["lineColors"]   = 
# default["graphite"]["templates"]["default"]["fontName"]     = 
# default["graphite"]["templates"]["default"]["fontSize"]     = 
# default["graphite"]["templates"]["default"]["fontBold"]     = 
# default["graphite"]["templates"]["default"]["fontItalic"]   = 